app/Http/routes.php
<?php
use App\User;
use App\Dies;


Route::get('/', function(){

	return redirect('dashboard');
});

Route::get('home', function()
{
    return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function()
{
	Route::get('dashboard', function(){
		
        $user = Auth::user();
        if($user->locations->count()){
            $location = $user->locations->first();
            return view('dashboard',compact('location'));
        }else{

            return view('no_permission',compact('user'));
        }
        
	});

    Route::get('reports/create/{type}','ReportsController@create');
    Route::get('reports/{report_id}/{action}','ReportsController@show');    

    Route::resource('reports','ReportsController');
    Route::resource('machines','MachinesController');
    Route::resource('dies','DiesController');
    Route::resource('coins','CoinsController');


});


Route::group(['prefix' => 'admin', 'middleware'=>'admin'], function()
{

    Route::get('dashboard', function()    {
        return view('admin.dashboard');
    });   


    //Route::post('users/{user_id}/attach/{location_id}','admin\AdminUsersController@attach');
    Route::post('users/attach','admin\AdminUsersController@attach');
    Route::post('users/{user_id}/remove/{location_id}','admin\AdminUsersController@remove');

    Route::resource('users','admin\AdminUsersController');
    
    Route::resource('companies','admin\AdminCompaniesController');
    Route::resource('locations','admin\AdminLocationsController');

    Route::get('locations/{location_id}/reports/create/{type}','admin\AdminReportsController@create');
    Route::get('locations/{location_id}/reports/{report_id}/edit','admin\AdminReportsController@edit');    
    Route::get('locations/{location_id}/reports/{report_id}/{action}','admin\AdminReportsController@show');    
    Route::resource('locations.reports','admin\AdminReportsController');    

    Route::resource('machines','admin\AdminMachinesController');
    Route::resource('machine_settings','admin\AdminMachineSettingsController');
    Route::resource('dies','admin\AdminDiesController');
    Route::resource('coins','admin\AdminCoinsController');
});



Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::get('get_dies/{location_id}', function($location_id){
    return \DB::table('dies')->where('location_id', $location_id)->get();

});

Route::get('get_coins/{location_id}', function($location_id){
    return \DB::table('coins')->where('location_id', $location_id)->get();

});

app/Company.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{


    protected $fillable = ['active','name', 'address', 'website', 'notes'];


    public function location()
    {

        return $this->hasMany('App\Location');
    }

    public function machine()
    {

        return $this->hasMany('App\Machine');
    }

}

resources/views/admin/companies/create.blade.php
@extends('admin.layout')

@section('main')
   <h1 class="page-header">Add New Company</h1>  

   
	{!! Form::open(['url'=>'admin/companies','class'=>'row']) !!}			
   		
   		@include('admin.companies.form',['submit_btn_text'=>'Add New Company'])
			
	{!!Form::close()!!}

@stop

resources/views/admin/companies/edit.blade.php
@extends('admin.layout')

@section('main')
   <h1 class="page-header">Edit {!! $company->name !!}</h1>  

   
	{!! Form::model($company,['method'=>'PATCH','url' => ['admin/companies',$company->id ], 'class'=>'row edit']) !!}
   		
   		@include('admin.companies.form',['submit_btn_text'=>'Update Company Info'])
			
	{!!Form::close()!!}
	
@stop

resources/views/admin/companies/form.blade.php
<div class="col-sm-4">
		
	@include('partial.form_error')

	
	<div class="form-group">				
		{!!Form::label('name','Company Name')!!}
		{!!Form::text('name',null,array('class'=>'form-control')) !!}   
	</div>

	<div class="form-group">				
		{!!Form::label('address','Company Address')!!}
		{!!Form::textarea('address',null,array('class'=>'form-control','rows'=>'3')) !!}   
	</div>

	<div class="form-group">				
		{!!Form::label('website','Website')!!}
		{!!Form::text('website',null,array('class'=>'form-control')) !!}   
	</div>

	

	<div class="form-group">				
		{!!Form::label('notes','Notes')!!}
		{!!Form::text('notes',null,array('class'=>'form-control')) !!}   
	</div>		

	
	<div class="form-group">
        @if(Request::is('admin/companies/*/edit'))
            <a href="{{ URL::route('admin.companies.show', $company->id) }}" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Cancel</a>
        @elseif(Request::is('admin/companies/create'))
            <a href="{{ URL::route('admin.companies.index') }}" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Cancel</a>
        @endif
		
		{!! Form::submit($submit_btn_text,['class'=>'btn btn-primary']) !!}
		
	</div>

</div>

@include('admin.companies.script')

resources/views/admin/companies/index.blade.php
@extends('admin.layout')

@section('main')
   <h1 class="page-header">Companies</h1>
   @if(!count($companies))
       <div class="col-sm-4">
           <p class="alert alert-warning">
               No companies found! Please
               <a href="{{ url('admin/companies/create')}}">create a company</a>
           </p>
       </div>
   @else
   	<?php $sl = 1; ?>
   	<table class="table table-striped table-bordered table_sortable">
        <thead>
        <tr><th>SL</th><th>Company Name</th><th>Locations</th><th>Machines</th><th>Action</th></tr>
        </thead>
	   	@foreach($companies as $company)
	   	<tr>
	   		<td>{{$sl++}}</td>
	   		<td>
	   			<a href="{{ URL::route('admin.companies.show',$company->id) }}">{{$company->name}}</a>
	   			
	   		</td>	
	   		<td>{{ App\Location::WHERE("company_id","=",$company->id)->WHERE("active","=","1")->count() }}</td>
	   		<td>{{--
                count(App\Company::JOIN("locations", "locations.company_id", "=", "companies.id")
                    ->WHERE("companies.id","=",$company->id)
                    ->JOIN("machines", "machines.location_id", "=", "locations.id")
                    ->WHERE("machines.active","=","1")
                    ->get())
	        
          --}}</td> <!--//TODO ask fida about making this more simple -->
	   		<td>
	   			
	   			<a href="{{ URL::route('admin.companies.edit',$company->id) }}" class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> Edit</a>&nbsp;&nbsp;
				<a title="delete" data-url="{{url('admin/companies/'.$company->id)}}" data-token="{{csrf_token()}}" class="admin_company_del_btn btn btn-xs btn-danger" href="#"><i class="glyphicon glyphicon-trash"></i> Delete</a> 

	   		</td>
	   	</tr>
	   	@endforeach
   	</table>

   @endif

    @include('admin.companies.script')
@stop

resources/views/admin/companies/script.blade.php
<script>
    $(document).ready(function(){

        /***
         *Delete company button
        * */

        $('.admin_company_del_btn').click(function(e){
            e.preventDefault();

            var target = $(this);
            var url = $(this).data('url');
            var token = $(this).data('token');




            alertify.confirm('Are you sure you want to delete this company? This action cannot be undone.').setting({
                'title':'<span class="glyphicon glyphicon-trash"></span> Delete Company',
                'labels':{ok:'DELETE'},
                'onok': function(){

                    $.ajax({

                        url: url,
                        type: 'POST',
                        data: {_method: 'delete', _token: token},

                        beforeSend:function(){

                            $(target).addClass('disabled');
                            $(target).parent().parent().css('opacity','.5');

                        },
                        success: function (res) {

                            if(res=='success'){

                                $(target).parent().parent().fadeOut(500,function(){
                                    $(target).parent().parent().remove();
                                });

                                alertify.success('Company has been deleted');
                                $('.nav-sidebar .badge.company').html(parseInt($('.nav-sidebar .badge.company').html())-1);

                            }else{

                                $(target).removeClass('disabled');
                                $(target).parent().parent().css('opacity','1');
                                alertify.error('Failed to delete company. <br>'+res);
                            }


                        }
                    });


                },
                'oncancel':function(){


                }
            });
        });

        /**
         * delete location from company show
        */
        $('.admin_location_del_btn').click(function(e){
            e.preventDefault();

            var target = $(this);
            var url = $(this).data('url');
            var token = $(this).data('token');




            alertify.confirm('Are you sure you want to delete this location? This action cannot be undone.').setting({
                'title':'<span class="glyphicon glyphicon-trash"></span> Delete Location',
                'labels':{ok:'DELETE'},
                'onok': function(){

                    $.ajax({

                        url: url,
                        type: 'POST',
                        data: {_method: 'delete', _token: token},

                        beforeSend:function(){

                            $(target).addClass('disabled');
                            $(target).parent().parent().css('opacity','.5');

                        },
                        success: function (res) {

                            if(res=='success'){

                                $(target).parent().parent().fadeOut(500,function(){
                                    $(target).parent().parent().slideUp();
                                });

                                alertify.success('Location has been deleted');
                                $('.nav-sidebar .badge.location').html(parseInt($('.nav-sidebar .badge.location').html())-1);

                            }else{

                                $(target).removeClass('disabled');
                                $(target).parent().parent().css('opacity','1');
                                alertify.error('Failed to delete location. <br>'+res);
                            }


                        }
                    });


                },
                'oncancel':function(){


                }
            });
        });

       

    });
</script>

resources/views/admin/companies/show.blade.php
@extends('admin.layout')

@section('main')
    <h1 class="page-header">{{ $company->name }}  <a href="{{ URL::route('admin.companies.edit',$company->id) }}" class="btn btn-xs"><i class="glyphicon glyphicon-pencil"></i></a>&nbsp;&nbsp;</h1>

    <h3 class="page-header">Locations</h3>
    @if(!count($locations))
        <div class="row">
            <div class="col-sm-4">
                <p class="alert alert-warning">
                    No locations found! Please
                    <a href="{{ url('admin/locations/create')}}">add a location</a>
                </p>
            </div>
        </div>
    @else
        <?php $sl = 1; ?>
        <table class="table table-striped table-bordered">
            <tr><th>SL</th><th>Location</th><th>Action</th></tr>
            @foreach($locations as $location)
                <tr>
                    <td>{{$sl++}}
                    <td>
                        @if($location->photo!='')
                            {!! Html::image('upload/75-'.$location->photo, $location->photo, array('class' => 'location_photo thumb pull-left')) !!}
                        @else
                            {!! Html::image('images/no_image_75x50.png', null, array('class' => 'location_photo thumb pull-left')) !!}
                        @endif

                        <a href="{{ URL::route('admin.locations.show',$location->id) }}">{{$location->name}}</a>
                        <p>{{$location->address}}</p>

                    </td>
                    <td>

                        <a href="{{ URL::route('admin.locations.edit',$location->id) }}" class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> Edit</a>&nbsp;&nbsp;
                        <a title="delete" data-url="{{url('admin/locations/'.$location->id)}}" data-token="{{csrf_token()}}" class="admin_location_del_btn btn btn-xs btn-danger" href="#"><i class="glyphicon glyphicon-trash"></i> Delete</a>

                    </td>
                </tr>

            @endforeach
        </table>
    @endif

    @include('admin.companies.script')

@stop