app/Http/routes.php
<?php
use App\User;
use App\Dies;


Route::get('/', function(){

	return redirect('dashboard');
});

Route::get('home', function()
{
    return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function()
{
	Route::get('dashboard', function(){
		
        $user = Auth::user();
        if($user->locations->count()){
            $location = $user->locations->first();
            return view('dashboard',compact('location'));
        }else{

            return view('no_permission',compact('user'));
        }
        
	});

    Route::get('reports/create/{type}','ReportsController@create');
    Route::get('reports/{report_id}/{action}','ReportsController@show');    

    Route::resource('reports','ReportsController');
    Route::resource('machines','MachinesController');
    Route::resource('dies','DiesController');
    Route::resource('coins','CoinsController');


});


Route::group(['prefix' => 'admin', 'middleware'=>'admin'], function()
{

    Route::get('dashboard', function()    {
        return view('admin.dashboard');
    });   


    //Route::post('users/{user_id}/attach/{location_id}','admin\AdminUsersController@attach');
    Route::post('users/attach','admin\AdminUsersController@attach');
    Route::post('users/{user_id}/remove/{location_id}','admin\AdminUsersController@remove');

    Route::resource('users','admin\AdminUsersController');
    
    Route::resource('companies','admin\AdminCompaniesController');
    Route::resource('locations','admin\AdminLocationsController');

    Route::get('locations/{location_id}/reports/create/{type}','admin\AdminReportsController@create');
    Route::get('locations/{location_id}/reports/{report_id}/edit','admin\AdminReportsController@edit');    
    Route::get('locations/{location_id}/reports/{report_id}/{action}','admin\AdminReportsController@show');    
    Route::resource('locations.reports','admin\AdminReportsController');    

    Route::resource('machines','admin\AdminMachinesController');
    Route::resource('machine_settings','admin\AdminMachineSettingsController');
    Route::resource('dies','admin\AdminDiesController');
    Route::resource('coins','admin\AdminCoinsController');
});



Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::get('get_dies/{location_id}', function($location_id){
    return \DB::table('dies')->where('location_id', $location_id)->get();

});

Route::get('get_coins/{location_id}', function($location_id){
    return \DB::table('coins')->where('location_id', $location_id)->get();

});

app/Http/Controllers/DiesController.php
<?php namespace App\Http\Controllers;

use App\Dies;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class DiesController extends Controller {

	
	public function index()
    {
        $user = \Auth::user();
        if($user->locations->count()){
            $location = $user->locations->first();
            $dies = $location->dies;
            
        	return view('dies.index',compact('dies','location'));
        }else{

            return view('no_permission',compact('user'));
        }


    }

	

}

resources/views/admin/dies/create.blade.php
@extends('admin.layout')

@section('main')
    <h1 class="page-header">Add New Dies</h1>

    <div class="row">

        {!! Form::open(['url'=>'admin/dies','files'=>'true','class'=>'col-sm-12 col-md-6 col-lg-5']) !!}

        @include('admin.dies.form',['submit_btn_text'=>'Add New Dies'])


        {!!Form::close()!!}
    </div>

@stop

resources/views/admin/dies/edit.blade.php
@extends('admin.layout')

@section('main')
    <h1 class="page-header">Edit Dies</h1>

    <div class="row">

        {!! Form::model($dies,['method'=>'PATCH','url' => ['admin/dies',$dies->id ],'files'=>'true', 'class'=>'col-sm-12 col-md-6 col-lg-5 edit']) !!}

        @include('admin.dies.form',['submit_btn_text'=>'Update Dies Info'])


        {!!Form::close()!!}
    </div>

@stop

resources/views/admin/dies/form.blade.php
<div class="form-group">

    @include('partial.form_error')

</div>

<!--
<div class="form-group row">

	<div class="col-sm-12">
		{!!Form::checkbox('stock',1,null,array('id'=>'stock')) !!}
		{!!Form::label('stock','Stock Die',array('class'=>'') )!!}

	</div>

</div>
-->
@if(isset($dies))
    <div class="form-group row">
        <div class="col-sm-6">
            {!! Html::image('upload/200-'.$dies->photo,$dies->photo,array('class'=>'dies_photo')) !!}
        </div>
    </div>
@endif

<div class="form-group row">
    <div class="col-sm-6">
        {!! Form::label('name','Dies Name') !!}
        {!! Form::text('name',null,array('class'=>'form-control') ) !!}
    </div>

    <div class="col-sm-6">
        {!! Form::label('location_id','Select Die Location') !!}
        {!! Form::select('location_id',$locations,null,array('class'=>'form-control searchable_select') ) !!}
    </div>
</div>

<div class="form-group row">
    <div class="col-xs-3">
        {!! Form::label('cabinet','Cabinet') !!}
        {!! Form::select('cabinet',array(
        'A'=>'A',
        'B'=>'B',
        'C'=>'C',
        'D'=>'D'
        ),null,array('class'=>'form-control') ) !!}
    </div>

    <div class="col-xs-3">
        {!! Form::label('drawer','Drawer') !!}
        {!! Form::selectRange('drawer',1,8,null,array('class'=>'form-control')) !!}
    </div>

    <div class="col-xs-3">
        {!! Form::label('row','Row') !!}
        {!! Form::select('row',array(
        'A'=>'A',
        'B'=>'B',
        'C'=>'C',
        'D'=>'D',
        'E'=>'E',
        'F'=>'F',
        'G'=>'G'
        ),null,array('class'=>'form-control') ) !!}
    </div>

    <div class="col-xs-3">
        {!! Form::label('col','Col') !!}
        {!! Form::selectRange('col',1,6,null,array('class'=>'form-control')) !!}
    </div>

</div>

<div class="form-group row">
    <div class="col-sm-6">
        {!! Form::label('photo','Upload Dies Photo') !!}
        {!! Form::file('photo',array('class'=>'form-control')) !!}
    </div>

    <div class="col-sm-6">
        <br> <p class="text-muted"><i class="glyphicon glyphicon-info-sign"></i>
            Dies photo size should be 200x200 pixel</p>
    </div>
</div>



<div class="form-group">
    <a href="{{ URL::route('admin.dies.index') }}" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Cancel</a>

    {!! Form::submit($submit_btn_text,['class'=>'btn btn-primary']) !!}

</div>

resources/views/admin/dies/index.blade.php
@extends('admin.layout')

@section('main')
    <h1 class="page-header">Dies</h1>


    @if(!count($dies))
        <div class="col-sm-4">
            <p class="alert alert-warning">
                No dies found! Please
                <a href="{{ url('admin/dies/create')}}">create a die</a>
            </p>
        </div>
    @else
        <?php $sl = 1; ?>
        <table class="table table-striped table-bordered dies">
            <tr>
                    <th>SL</th><th>Dies</th><th>Location</th><th>Action</th>
            </tr>
            @foreach($dies as $item)
                <tr>
                    <td>{{$sl++}}</td>
                    <td>

                        {!! Html::image('upload/50-'.$item->photo, $item->photo, array('class' => 'dies_photo thumb pull-left')) !!}

                        <h4 class="name">{{$item->name}}</h4>

                        <h5 title="cabinet drawer row col">{{ $item->cabinet.' '.$item->drawer.' '.$item->row.' '.$item->col}}</h5>
                    </td>

                    <td>
                        @if($item->location_id == 0)
                            Stock Die
                        @else
                            <a href="{{ URL::route('admin.locations.show',$item->location->id) }}">{{ $item->location->name }}</a>
                        @endif
                    </td>

                    <td>

                        <a href="{{ URL::route('admin.dies.edit',$item->id) }}" class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> Edit</a>&nbsp;&nbsp;
                        <a title="delete" data-url="{{url('admin/dies/'.$item->id)}}" data-token="{{csrf_token()}}" class="admin_dies_del_btn btn btn-xs btn-danger" href="#"><i class="glyphicon glyphicon-trash"></i> Delete</a>

                    </td>
                </tr>
            @endforeach
        </table>

    @endif

    @include('admin.dies.script')

@stop

resources/views/admin/dies/script.blade.php
<script>
    $(document).ready(function(){



        $('.admin_dies_del_btn').click(function(e){
            e.preventDefault();

            var target = $(this);
            var url = $(this).data('url');
            var token = $(this).data('token');

            alertify.confirm('Are you sure you want to delete this Dies ? This action cannot be undone.').setting({
                'title':'<span class="glyphicon glyphicon-trash"></span> Delete Dies',
                'labels':{ok:'DELETE'},
                'onok': function(){

                    $.ajax({

                        url: url,
                        type: 'POST',
                        data: {_method: 'delete', _token: token},

                        beforeSend:function(){

                            $(target).addClass('disabled');
                            $(target).parent().parent().css('opacity','.5');

                        },
                        success: function (res) {

                            if(res=='success'){

                                $('.nav-sidebar .badge.dies').html(parseInt($('.nav-sidebar .badge.dies').html())-1);

                                $(target).parent().parent().fadeOut(500,function(){
                                    $(target).parent().parent().remove();
                                });

                                alertify.success('Dies has been deleted');

                            }else{

                                $(target).removeClass('disabled');
                                $(target).parent().parent().css('opacity','1');
                                alertify.error('Failed to delete dies. <br>'+res);
                            }


                        }
                    });


                },
                'oncancel':function(){


                }
            });
        });




    });
</script>