app/Http/routes.php
<?php
use App\User;
use App\Dies;


Route::get('/', function(){

	return redirect('dashboard');
});

Route::get('home', function()
{
    return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function()
{
	Route::get('dashboard', function(){
		
        $user = Auth::user();
        if($user->locations->count()){
            $location = $user->locations->first();
            return view('dashboard',compact('location'));
        }else{

            return view('no_permission',compact('user'));
        }
        
	});

    Route::get('reports/create/{type}','ReportsController@create');
    Route::get('reports/{report_id}/{action}','ReportsController@show');    

    Route::resource('reports','ReportsController');
    Route::resource('machines','MachinesController');
    Route::resource('dies','DiesController');
    Route::resource('coins','CoinsController');


});


Route::group(['prefix' => 'admin', 'middleware'=>'admin'], function()
{

    Route::get('dashboard', function()    {
        return view('admin.dashboard');
    });   


    //Route::post('users/{user_id}/attach/{location_id}','admin\AdminUsersController@attach');
    Route::post('users/attach','admin\AdminUsersController@attach');
    Route::post('users/{user_id}/remove/{location_id}','admin\AdminUsersController@remove');

    Route::resource('users','admin\AdminUsersController');
    
    Route::resource('companies','admin\AdminCompaniesController');
    Route::resource('locations','admin\AdminLocationsController');

    Route::get('locations/{location_id}/reports/create/{type}','admin\AdminReportsController@create');
    Route::get('locations/{location_id}/reports/{report_id}/edit','admin\AdminReportsController@edit');    
    Route::get('locations/{location_id}/reports/{report_id}/{action}','admin\AdminReportsController@show');    
    Route::resource('locations.reports','admin\AdminReportsController');    

    Route::resource('machines','admin\AdminMachinesController');
    Route::resource('machine_settings','admin\AdminMachineSettingsController');
    Route::resource('dies','admin\AdminDiesController');
    Route::resource('coins','admin\AdminCoinsController');
});



Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::get('get_dies/{location_id}', function($location_id){
    return \DB::table('dies')->where('location_id', $location_id)->get();

});

Route::get('get_coins/{location_id}', function($location_id){
    return \DB::table('coins')->where('location_id', $location_id)->get();

});

app/Machine.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Coin;
use App\MachineSettings;

class Machine extends Model {

	protected $fillable = ['location_id','name', 'photo', 'specific_location',
		'asset_num_1','asset_num_2','date_shipped','date_installed',

		'machine_types','machine_colors','machine_keys','prices','motors','button_lights',

		'coins','coin_1','coin_2','coin_3','coin_4',

		'gizmo_models','gizmo_serial','meter_box_models','meter_box_serial','gizmo_fws','gizmo_pic',

		'has_cc','cc_companies','cc_antennas','cc_modem_models','cc_modem_serial','cc_reader_models','cc_reader_serial',

		'bill_validator_models','vault_models','vault_keys','bill_validator_serial','vault_serial',

		'hopper_models_1','hopper_models_2','hopper_models_3','hopper_models_4',
		'hopper_serial_1','hopper_serial_2','hopper_serial_3','hopper_serial_4',

		'current_meter_1','current_meter_2','current_meter_3','current_meter_4','current_meter_5','current_meter_6',
		'starting_meter_1','starting_meter_2','starting_meter_3','starting_meter_4','starting_meter_5','starting_meter_6',

		'shipped_meter_1','shipped_meter_2','shipped_meter_3','shipped_meter_4','shipped_meter_5','shipped_meter_6',
		'shipped_coin_1_id','shipped_coin_2_id','shipped_coin_3_id','shipped_coin_4_id',
		'shipped_coin_1_quantity','shipped_coin_2_quantity','shipped_coin_3_quantity','shipped_coin_4_quantity'

	];

	public function location(){

		return $this->belongsTo('App\Location');
	}

	public function price(){
		$data = json_decode(MachineSettings::where('id',$this->prices)->first()->data);		
		return $data->prices;
	}

	public function price_min(){
		$data = json_decode(MachineSettings::where('id',$this->prices)->first()->data);
		return round($data->level_2_credit/$data->level_2_coin,2);		
	}

	public function price_max(){		
		
		$data = json_decode(MachineSettings::where('id',$this->prices)->first()->data);		
		return round($data->level_1_credit/$data->level_1_coin,2);
	}

	public function coin_1(){
		return Coin::where('id','=',$this->coin_1)->first();
	}

	public function coin_2(){
		return Coin::where('id','=',$this->coin_2)->first();
	}

	public function coin_3(){
		return Coin::where('id','=',$this->coin_3)->first();
	}

	public function coin_4(){
		return Coin::where('id','=',$this->coin_4)->first();
	}


	

}

app/Http/Controllers/MachinesController.php
<?php namespace App\Http\Controllers;

use App\Machine;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class MachinesController extends Controller {

	
	public function index()
    {
        $user = \Auth::user();
        if($user->locations->count()){
            $location = $user->locations->first();
            $machines = $location->machine;
            
        	return view('machines.index',compact('machines','location'));
        }else{

            return view('no_permission',compact('user'));
        }


    }

	

}

resources/views/admin/machines/create.blade.php
@extends('admin.layout')

@section('main')
    <h1 class="page-header">Add New Machine</h1>

    @include('partial.form_error')

    {!! Form::open(['url'=>'admin/machines','files'=>'true','class'=>'machine_form']) !!}

        @if(!count($locations))            
            <p class="alert alert-warning">
                No Location found! Please <a href="{{ url('admin/locations/create')}}">create a location</a>
                first , then you can add machine
            </p>            
        @else

            @include('admin.machines.form')
        
            <div class="form-group">
                {!! Form::submit('Create New Machine',['class'=>'btn btn-primary']) !!}
            </div>
        @endif

    {!!Form::close()!!}
    
    @include('admin.machines.machine_setting_add')
    @include('admin.machines.script')

@stop

resources/views/admin/machines/edit.blade.php
@extends('admin.layout')

@section('main')
    <h1 class="page-header">Edit Machine</h1>

    @include('partial.form_error')

    {!! Form::model($machine,['method'=>'PATCH','url' => ['admin/machines',$machine->id ],'files'=>'true', 'class'=>'machine_form']) !!}
        

        @include('admin.machines.form')
    
        <div class="form-group">
            {!! Form::submit('Update Machine',['class'=>'btn btn-primary']) !!}
        </div>
        

    {!!Form::close()!!}

    @include('admin.machines.machine_setting_add')
    
    @include('admin.machines.script')

@stop

resources/views/admin/machines/form.blade.php
<div role="tabpanel">
    
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#details" aria-controls="details" role="tab" data-toggle="tab">Details</a></li>
        <li role="presentation"><a href="#coins" aria-controls="coins" role="tab" data-toggle="tab">Coins</a></li>
        <li role="presentation"><a href="#gizmo" aria-controls="gizmo" role="tab" data-toggle="tab">Gizmo</a></li>
        <li role="presentation"><a href="#credit_card" aria-controls="credit_card" role="tab" data-toggle="tab">Credit Card</a></li>
        <li role="presentation"><a href="#bill_validator" aria-controls="bill_validator" role="tab" data-toggle="tab">Bill Validator</a></li>
        <li role="presentation"><a href="#hoppers" aria-controls="hoppers" role="tab" data-toggle="tab">Hoppers</a></li>
        <li role="presentation"><a href="#meters" aria-controls="meters" role="tab" data-toggle="tab">Meters</a></li>
        <li role="presentation"><a href="#shipped" aria-controls="shipped" role="tab" data-toggle="tab">Shipped</a></li>
        <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">History</a></li>
    </ul>

    <div class="tab-content">
        
        <div role="tabpanel" class="tab-pane fade in active" id="details">
            @include('admin.machines.form_tabs.details')
        </div>
        
        <div role="tabpanel" class="tab-pane fade" id="coins">
            @include('admin.machines.form_tabs.coins')
        </div>

        <div role="tabpanel" class="tab-pane fade" id="gizmo">
            @include('admin.machines.form_tabs.gizmo')
        </div>

        <div role="tabpanel" class="tab-pane fade" id="credit_card">
            @include('admin.machines.form_tabs.credit_card')
        </div>

        <div role="tabpanel" class="tab-pane fade" id="bill_validator">
            @include('admin.machines.form_tabs.bill_validator')
        </div>

        <div role="tabpanel" class="tab-pane fade" id="hoppers">
            @include('admin.machines.form_tabs.hoppers')
        </div>

        <div role="tabpanel" class="tab-pane fade" id="meters">
            @include('admin.machines.form_tabs.meters')
        </div>

        <div role="tabpanel" class="tab-pane fade" id="shipped">
            @include('admin.machines.form_tabs.shipped')
        </div>

        <div role="tabpanel" class="tab-pane fade" id="history">
            @include('admin.machines.form_tabs.history')
        </div>        

    </div>
    
</div>

resources/views/admin/machines/index.blade.php
@extends('admin.layout')

@section('main')
   <h1 class="page-header">Machines</h1>
   @if(!count($machines))
       
     <p class="alert alert-warning">
         No machines found! 
         <a href="{{ url('admin/machines/create')}}">Add new machine</a>
     </p>
       
   @else
   	<?php $sl = 1; ?>
   	<table class="table table-striped table-bordered table_sortable">
        <thead>
            <tr><th>SL</th><th>Machines</th><th>Location</th><th>Company</th><th>Action</th></tr>
        </thead>
	   	@foreach($machines as $machine)
	   	<tr>
	   		<td>{{$sl++}}</td>
        <td>
	        @if($machine->photo!='')
		        {!! Html::image('upload/50-'.$machine->photo, $machine->photo, array('class' => 'machine_photo thumb pull-left')) !!}
	        @else
		        {!! Html::image('images/no_image_75x50.png', null, array('class' => 'machine_photo thumb pull-left')) !!}
	        @endif
          <a href="{{ URL::route('admin.machines.edit',$machine->id) }}">{{ $machine->name }}</a>
        </td>

        <td>          
          <a href="{{ URL::route('admin.locations.show',$machine->location->id) }}">{{ $machine->location->name }}</a>
        </td>


	   		<td>	   		  
          <a href="{{ URL::route('admin.companies.show',$machine->location->company->id) }}">{{ $machine->location->company->name }}</a>
	   		</td>

        

	   		<td>	   			
	   			<a href="{{ URL::route('admin.machines.edit',$machine->id) }}" class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> Edit</a>&nbsp;&nbsp;
				  <a title="delete" data-url="{{url('admin/machines/'.$machine->id)}}" data-token="{{csrf_token()}}" class="admin_machine_del_btn btn btn-xs btn-danger" href="#"><i class="glyphicon glyphicon-trash"></i> Delete</a> 
	   		</td>
	   	</tr>
	   	@endforeach
   	</table>

   @endif

   @include('admin.machines.script')
@stop

resources/views/admin/machines/machine_setting_add.blade.php
<!-- Modal -->
<div class="add_setting modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  {!! Form::open(['url'=>'admin/machine_settings','class'=>'add_setting_form']) !!}
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>

      <div class="modal-body"></div>
               
        

    </div>
  </div>
  {!! Form::close()!!}
</div>

<table class="table table-bordered table-striped add_setting_step machine_types">    
    <thead> <tr><th>Machine Type</th><th></th></tr> </thead>
    <tbody>
        <tr>                         
            <td><input name="type" class="form-control" placeholder="Enter Machine Type" required></td>                 
        </tr>                                        
    </tbody>    
</table>

<table class="table  table-bordered table-striped add_setting_step machine_colors">
    <thead> <tr><th>Type</th><th>SW Code</th><th>Color</th><th></th></tr> </thead>
    <tbody>
        <tr>
            <td>
                <select name="type" class="form-control" required>
                    <option value="">Please Select Type</option>
                    <option value="Clear Coat">Clear Coat</option>
                    <option value="Paint">Paint</option>
                    <option value="Stain">Stain</option>
                </select>
            </td>
            <td><input name="sw_code" class="form-control" placeholder="SW Code" required> </td> 
            <td><input name="color" class="form-control" placeholder="Color" required></td>            
        </tr>        
    </tbody>    
</table>


<table class="table table-striped table-bordered add_setting_step machine_keys">
    <thead><tr><th>Machine Keys</th><th></th> </tr></thead>

    <tbody>
        <tr>
            <td><input name="machine_key" class="form-control" placeholder="Machine Key" required></td>            
        </tr>                              
    </tbody>
    
</table>


<table class="table table-striped table-bordered add_setting_step prices">
    <thead>
        <tr>
          <th>Prices</th>
          <th colspan="2" style="text-align:center;">Level 1</th>
          <th colspan="2" style="text-align:center;">Level 2</th>         
          <th></th></tr>

    </thead>

    <tbody>
        <tr>                            
            <td><input name="prices" class="form-control" placeholder="Prices" required style="width:140px;"></td>
            <td><input name="level_1_credit" class="form-control" placeholder="$" required></td>
            <td><input name="level_1_coin" class="form-control" placeholder="#coin" required></td>
            <td><input name="level_2_credit" class="form-control" placeholder="$" required></td>
            <td><input name="level_2_coin" class="form-control" placeholder="#coin" required></td>                 
        </tr>                        
    </tbody>    
</table>


<table class="table table-striped table-bordered add_setting_step motors">
    <thead>
        <tr><th>Company</th><th>Voltage</th><th></th></tr>
    </thead>

    <tbody>
        <tr>
            <td><input name="company" class="form-control" placeholder="Company" required></td>
            <td><input name="voltage" class="form-control" placeholder="Voltage" required></td>           
        </tr>                        
    </tbody>
    
</table>


<table class="table table-striped table-bordered add_setting_step button_lights">
    <thead>
        <tr><th>Company</th><th>Type</th><th></th></tr>
    </thead>

    <tbody>
        <tr>                              
            <td><input name="company" class="form-control" placeholder="Company" required></td>
            <td><input name="type" class="form-control" placeholder="Type" required></td>           
        </tr>                
    </tbody>
    
</table>

<table class="table table-striped table-bordered add_setting_step gizmo_models">
    <thead>
        <tr><th>Company</th><th>Model</th><th></th></tr>
    </thead>

    <tbody>
        <tr>                              
            <td><input name="company" class="form-control" placeholder="Company" required></td>
            <td><input name="model" class="form-control" placeholder="Model" required></td>
        </tr>
    </tbody>
    
</table>

<table class="table table-striped table-bordered add_setting_step meter_box_models">
    <thead>
        <tr><th>Company</th><th>Model</th><th></th></tr>
    </thead>

    <tbody>
        <tr>                            
            <td><input name="company" class="form-control" placeholder="Company" required></td>
            <td><input name="model" class="form-control" placeholder="Model" required></td>            
        </tr>                        
    </tbody>
    
</table>

<table class="table table-striped table-bordered add_setting_step gizmo_fws">
    <thead>
        <tr><th>Gizmo FWS</th><th></th></tr>
    </thead>

    <tbody>
        <tr>                           
            <td><input name="gizmo_fws" class="form-control" placeholder="Gizmo FWS" required></td>                            
        </tr>                        
    </tbody>
    
</table>

 <table class="table table-striped table-bordered add_setting_step cc_companies">
    <thead>
        <tr><th>Credit Card Company</th><th></th></tr>
    </thead>

    <tbody>
        <tr>
            <td><input name="cc_company" class="form-control" placeholder="Credit Card Company" required></td>            
        </tr>                        
    </tbody>
    
</table>


<table class="table table-striped table-bordered add_setting_step cc_modem_models">
    <thead>
        <tr><th>Company</th><th>Model</th><th></th></tr>
    </thead>

    <tbody>
        <tr>
            <td><input name="company" class="form-control" placeholder="Company" required></td>
            <td><input name="model" class="form-control" placeholder="Model" required></td>            
        </tr>                        
    </tbody>
    
</table>

<table class="table table-striped table-bordered add_setting_step cc_reader_models">
    <thead>
        <tr><th>Company</th><th>Model</th><th></th></tr>
    </thead>

    <tbody>

        <tr>
            <td><input name="company" class="form-control" placeholder="Company" required></td>
            <td><input name="model" class="form-control" placeholder="Model" required></td>           
        </tr>                        
    </tbody>
    
</table>

 <table class="table table-striped table-bordered add_setting_step cc_antennas">
    <thead>
        <tr><th>Credit Card Antena</th><th></th></tr>
    </thead>

    <tbody>
        <tr>                           
            <td><input name="cc_antena" class="form-control" placeholder="Credit Card Antena" required></td>           
        </tr>                        
    </tbody>
    
</table>


<table class="table table-striped table-bordered add_setting_step bill_validator_models">
    <thead>
        <tr><th>Company</th><th>Model</th><th>Type</th><th></th></tr>
    </thead>

    <tbody>

        <tr>                         
            <td><input name="company" class="form-control" placeholder="Company" required></td>
            <td><input name="model" class="form-control" placeholder="Model" required></td>
            <td>
                <select name="type" class="form-control" required>
                    <option value="">Please Select Type</option>
                    <option value="MDB">MDB</option>
                    <option value="Pulse">Pulse</option>
                </select>
            </td>           
        </tr> 
    </tbody>
    
</table>

<table class="table table-striped table-bordered add_setting_step vault_models">
    <thead>
        <tr><th>Company</th><th>Model</th><th>Lockable</th><th></th></tr>
    </thead>

    <tbody>

        <tr>                           
            <td><input name="company" class="form-control" placeholder="Company" required></td>
            <td><input name="model" class="form-control" placeholder="Model" required></td>
            <td>
                <select name="lockable" class="form-control" required>
                    <option value="">Please Select</option>
                    <option value="Yes">Yes</option>
                    <option value="No">No</option>
                </select>
            </td>
        </tr>                       
    </tbody>
    
</table>

<table class="table table-striped table-bordered add_setting_step vault_keys">
    <thead>
        <tr><th>Vault Keys</th><th></th></tr>
    </thead>

    <tbody>
        <tr>                             
            <td><input name="vault_key" class="form-control" placeholder="Vault Key" required></td> 
        </tr>                
    </tbody>
    
</table>


<table class="table table-striped table-bordered add_setting_step hopper_models">
    <thead>
        <tr><th>Company</th><th>Model</th><th>Size</th><th>Power</th><th></th></tr>
    </thead>

    <tbody>

        <tr>                            
            <td><input name="company" class="form-control" placeholder="Company" required></td>
            <td><input name="model" class="form-control" placeholder="Model" required></td>
            <td>
                <select name="size" class="form-control" required>
                    <option value="">Please Select</option>
                    <option value="28mm">28mm</option>
                    <option value="39mm">39mm</option>
                </select>
            </td>
             <td>
                <select name="power" class="form-control" required>
                    <option value="">Please Select</option>
                    <option value="24 V">24 V</option>
                    <option value="110 V">110 V</option>
                </select>
            </td>            
        </tr>                

        
    </tbody>
    
</table>

resources/views/admin/machines/machine_setting_fetch.blade.php
<select name="{{$name}}" id="{{$name}}" class="form-control {{$setting}}">


    <option value="">Please Select</option>
    @if( isset($machine_settings[$setting]) )
        @foreach($machine_settings[$setting] as $item)             
           
            @if(old($name))
                @if(old($name)==$item['id'])
                    <option value="{{$item['id']}}" selected>
                @else
                    <option value="{{$item['id']}}">
                @endif
            @elseif(isset($machine))
                @if($machine->$name == $item['id'])
                    <option value="{{$item['id']}}" selected>
                @else
                    <option value="{{$item['id']}}">
                @endif
            @else
                <option value="{{$item['id']}}">

            @endif
           
            
                <?php $sl=0; ?>
                @foreach(json_decode($item['data']) as $key=>$value)
                    {{($sl++>0?' | ':'').$value}}
                @endforeach
            </option>
            
        @endforeach
    @endif
</select>

resources/views/admin/machines/script.blade.php
<script type="text/javascript">
	$(document).ready(function(){
		
		/************ has_cc **************/	
		if( $('select#has_cc').val() !='1' ){
			$('.cc_details').hide();
		}

		$('select#has_cc').change(function(){
			$('.cc_details').toggle();
		});
		/*****************************************/

		function change_coin_number(coins){
			$('.coin_wrapper,.hopper_models_wrapper,.current_meter_wrapper,.shipped_meter_wrapper').hide();

			$('.current_meter_wrapper_1').show();
			$('.current_meter_wrapper_2').show();

			for(var i =1;i<=coins;i++){
				$('.coin_wrapper_'+i).show();
				$('.hopper_models_wrapper_'+i).show();
				$('.current_meter_wrapper_'+(i+2) ).show();
				$('.shipped_meter_wrapper_'+i).show();
			}
		}

		function set_coins(location_id){
			
			if(location_id){
				$('.location_select_warning').hide();
			}else{
				$('.location_select_warning').show();

				return;
			}
			
			$.getJSON("{{url('get_coins')}}"+'/'+location_id, null, function(data) {			
			    
			    if(data.length){			    	
			       	$('.location_has_coins_warning').hide();
			    }else{
			       	alertify.alert('Your selected location doesn\'nt have any coins yet, Please add coins at this location then try again');
			       	$('.location_has_coins_warning').show();
			    }

			    $(".coin option").remove();
			    
			    $(".coin").append( $("<option value>Please Select</option>") );
			    $.each(data, function(index, item) { 			        
			        $(".coin").append( $("<option ></option>").text(item.name).val(item.id)  );
			    });

			    @for($i=1;$i<=4;$i++)
			    	
			    	@if(old('coin_'.$i))
			    		$('#coin_'+{{$i}}).val( {{ old('coin_'.$i) }} );
			    	@elseif(isset($machine))
			    		$('#coin_'+{{$i}}).val( {{ $machine->{'coin_'.$i} }} );
			    	@endif
			    				    	
			    @endfor

			});
		}


		
		change_coin_number($('#coins :selected').val());		
		set_coins($('#location_id').val());
		
		$('#coins').change(function(){					
			change_coin_number($(':selected',this).val());			
		});

		$('#location_id').change(function(){
			var location_id = $('#location_id').val();			
			set_coins(location_id);
		});

		$('.no_coin_refresh_link').click(function(e){
			e.preventDefault();
			set_coins($('#location_id').val());
		});


		/*****************************************************************************************/
		var working_setting_item;

		$('.btn_add_setting').click(function(e){
			e.preventDefault();
			var setting = $(this).closest('.row').data('setting');
			working_setting_item = $(this).closest('.row').find('select');

			$('.modal.add_setting .modal-title').html('Add new '+setting.replace('_',' '));
			
			var content = $('.add_setting_step.'+setting).clone().show().removeClass('add_setting_step');

			$(content).find('tbody tr').append('<td>'+
                '<input type="hidden" name="setting" value="'+setting+'">'+
                '<button type="submit" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-plus"></i> Add New </button>'+
            '</td>');

			$('.modal.add_setting .modal-body').html(content);

			$('.modal.add_setting').modal('show');

		});

		$('.add_setting_form').submit(function(e){
			e.preventDefault();

			$('.btn_add_setting').attr('disabled','disabled');

			var url = $(this).attr('action');
            var data = $(this).serializeArray();
            
            $.ajax({
                url: url,
                type: 'POST',
                data: data,                
                success:function(res){
                	var new_opt_text = '';
                    var fields = $.parseJSON(res.data);
                    var sl = 0;                   
                    $.each(fields,function(i){   
                    	new_opt_text+= (sl++>0?' | ':'')+fields[i]                    	
                    }); 

                    if( $(working_setting_item).hasClass('hopper_models')){
                    	$('select.hopper_models').append('<option value="'+res.id+'">'+new_opt_text+'</option>');
                    	$(working_setting_item).val(res.id);
                    }else{
                    	$(working_setting_item).append('<option value="'+res.id+'" selected>'+new_opt_text+'</option>');
                    }
					
                    alertify.success('New machine setting item added');

                    $('.btn_add_setting').removeAttr('disabled');
                }
            });
			
			$('.modal.add_setting').modal('hide');
            
		});


		/**
		 * delete machine
		 */

		$('.admin_machine_del_btn').click(function(e){
			e.preventDefault();

			var target = $(this);
			var url = $(this).data('url');
			var token = $(this).data('token');




			alertify.confirm('Are you sure you want to delete this machine? This action cannot be undone.').setting({
				'title':'<span class="glyphicon glyphicon-trash"></span> Delete Machine',
				'labels':{ok:'DELETE'},
				'onok': function(){

					$.ajax({

						url: url,
						type: 'POST',
						data: {_method: 'delete', _token: token},

						beforeSend:function(){

							$(target).addClass('disabled');
							$(target).parent().parent().css('opacity','.5');

						},
						success: function (res) {

							if(res=='success'){

								$(target).parent().parent().fadeOut(500,function(){
									$(target).parent().parent().slideUp();
								});

								alertify.success('Machine has been deleted');
								$('.nav-sidebar .badge.machine').html(parseInt($('.nav-sidebar .badge.machine').html())-1);

							}else{

								$(target).removeClass('disabled');
								$(target).parent().parent().css('opacity','1');
								alertify.error('Failed to delete machine. <br>'+res);
							}


						}
					});


				},
				'oncancel':function(){


				}
			});
		});
			
		
	});
</script>